/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'jresendiz' at '4/20/17 11:17 PM' with Gradle 3.0
 *
 * @author jresendiz, @date 4/20/17 11:17 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
